<template>
  <div class="core" :class="coreClass">
    <canvas ref="canvas" class="core__canvas" aria-hidden="true"></canvas>
    <!--
      The status text is the accessible channel, so it must announce: wake,
      start-of-listening and start-of-thinking all happen without the user doing
      anything, and a screen-reader user with no notification of them simply does
      not know the microphone opened. Only this one element is a live region --
      TopBar repeats the same label and would announce it twice.
    -->
    <div class="core__readout" role="status" aria-live="polite" aria-atomic="true">
      <span class="core__state">{{ voice.label }}</span>
      <span class="core__hint">{{ caption }}</span>
      <!--
        Only a page that is itself the loudspeaker can stop the sentence. When the
        audio is coming out of Python's PortAudio stream, this window has no way to
        retract it and a button implying otherwise would be a lie with an icon on it.
      -->
      <button
        v-if="talking && isBrowserOutput"
        class="hud-btn core__stop"
        type="button"
        @click="stopSpeech"
      >
        停下
      </button>
      <!--
        Preview mode only, and labelled as a preview wherever it renders. Without a
        desktop shell there is no synthesis and no answer to speak, so the only way to
        see this crown move in a browser is to feed it samples here -- which proves
        the transport and the analyser, and proves nothing at all about the content.
      -->
      <button
        v-if="runningMocked"
        class="hud-btn core__stop"
        type="button"
        :disabled="previewing"
        @click="startPreviewSpeech()"
      >
        试听
      </button>
    </div>
  </div>
</template>

<script setup lang="ts">
/**
 * The voice core: the window's single point of gravity, and the one element whose
 * only job is to answer "what is it doing with my voice right now".
 *
 * It now has a real signal to answer with. This component used to draw rings and
 * arcs and refuse to draw a waveform, because the samples went out of Python into
 * the sound card and never passed anywhere the page could observe -- a lively wave
 * drawn from a state machine would have been the most convincing possible way to
 * lie about listening. The assistant's voice is now synthesized *here*, through an
 * AnalyserNode, so the crown of bars is a measurement: it is generated by exactly
 * the signal the operator hears, which is also what makes the avatar's mouth in the
 * next step capable of meaning something.
 *
 * Four rules the implementation exists to honour:
 *
 * * **No level, no motion.** When this page is not the output device the core falls
 *   back to state-driven rings, and the readout says 「无实时电平」. A bar chart of
 *   nothing is not a decoration, it is a claim.
 * * **It repaints when the state changes, even with animation switched off.**
 *   A user who asked for reduced motion asked for less movement, not for a picture
 *   that contradicts the text next to it.
 * * **It does not burn frames while idle.** This window is expected to stay open
 *   for hours; a 60 Hz loop that redraws identical pixels is pure cost. It runs fast
 *   only while sound is actually playing.
 * * **The analyser is read, never sampled into reactive state.** A ref updated 30
 *   times a second would re-render the whole panel tree to move one circle.
 */
import { computed, onBeforeUnmount, onMounted, ref, watch } from 'vue'
import { useVoiceStore } from '@/stores/voice'
import { runningMocked } from '@/api/bridge'
import {
  isBrowserOutput,
  levels,
  markTalking,
  previewing,
  startPreviewSpeech,
  stopSpeech,
  talking,
} from '@/audio/channel'

/** A closed set on purpose: a typo in a mood name must be a compile error rather
 *  than a core that silently stays "standby" forever. */
type MoodKey =
  | 'dormant'
  | 'waking'
  | 'armed'
  | 'listening'
  | 'thinking'
  | 'broken'
  | 'held'
  | 'error'

interface Mood {
  /** Base radius as a fraction of the half-width, and how much it breathes. */
  radius: number
  breath: number
  /** Degrees per second applied to the orbiting arcs. Zero means "static". */
  spin: number
  color: readonly [number, number, number]
  /** Segments of the outer ring that are drawn, out of twelve. */
  segments: number
  /**
   * Vertical squash of the orbit, 1 = a circle. A tilted ellipse reads as a body
   * moving in three dimensions, which is what distinguishes "working on it" from
   * "sitting ready" -- two states that otherwise both look like a ring going round.
   */
  tilt: number
}

const MOODS: Record<MoodKey, Mood> = {
  dormant: { radius: 0.44, breath: 0.006, spin: 0, color: [107, 139, 164], segments: 3, tilt: 1 },
  waking: { radius: 0.46, breath: 0.02, spin: 96, color: [255, 181, 71], segments: 12, tilt: 0.55 },
  armed: { radius: 0.5, breath: 0.035, spin: 12, color: [77, 216, 255], segments: 8, tilt: 1 },
  listening: { radius: 0.56, breath: 0.085, spin: 40, color: [70, 230, 168], segments: 12, tilt: 1 },
  thinking: { radius: 0.52, breath: 0.03, spin: 168, color: [157, 124, 255], segments: 12, tilt: 0.42 },
  broken: { radius: 0.5, breath: 0.02, spin: 24, color: [255, 181, 71], segments: 4, tilt: 0.8 },
  held: { radius: 0.44, breath: 0.004, spin: 0, color: [107, 139, 164], segments: 6, tilt: 1 },
  error: { radius: 0.44, breath: 0.008, spin: 0, color: [255, 93, 93], segments: 2, tilt: 1 },
}

/**
 * Anything at or below this spin rate is visually indistinguishable from still, so
 * it is drawn once and left alone. `dormant`, `held` and `error` land here: the
 * states a machine sits in for hours.
 */
const ANIMATED_BELOW = 8
/** Enough for a calm pulse; the eye does not need 60 Hz to believe it is alive. */
const FRAME_INTERVAL_MS = 66
/** While it is speaking: an amplitude envelope needs about 30 Hz to look continuous. */
const SPEAKING_FRAME_INTERVAL_MS = 33

const voice = useVoiceStore()
const canvas = ref<HTMLCanvasElement | null>(null)

/**
 * Availability and turn decide the mood -- not ``voice.error``, which is the
 * generic bridge-failure field. A failed 「清空」 click is not the microphone
 * being unavailable, and painting the indicator red for it teaches the operator
 * to distrust the one light that matters.
 */
const current = computed<MoodKey>((): MoodKey => {
  switch (voice.phase) {
    case 'loading':
      return 'waking'
    case 'failed':
      return 'error'
    case 'muted':
      return 'held'
    case 'running':
      if (voice.interrupted) return 'broken'
      if (voice.turn === 'listening') return 'listening'
      if (voice.turn === 'processing') return 'thinking'
      return 'armed'
    default:
      return 'dormant'
  }
})

/** ``hint`` already folds in the bridge error and the loading detail. */
const caption = computed(() => {
  if (previewing.value) return '预览信号：浏览器里合成的，不是它说的话'
  if (speakingSomewhere.value && !isBrowserOutput.value) return '回答正从本机扬声器播出，界面读不到电平'
  return voice.hint
})

/**
 * Whether it is talking *at all*, including when the sound is coming out of Python.
 *
 * The page only ever sees its own audio graph, so samples it is not playing have to
 * be inferred from the turn state. That is a weaker claim than a measurement, and the
 * caption says so instead of showing a still picture and letting the operator assume
 * silence.
 */
const speakingSomewhere = computed(
  () => talking.value || (voice.enabled && voice.turn === 'processing'),
)

/**
 * ``speaking`` is layered on rather than replacing a mood: "it is answering" and
 * "it is thinking" are different questions and both are still true at once.
 */
const coreClass = computed(() =>
  speakingSomewhere.value ? `core--${current.value} core--speaking` : `core--${current.value}`,
)

const TAU = Math.PI * 2
let reduced = false
let timer: ReturnType<typeof setInterval> | undefined
let observer: ResizeObserver | undefined
let mediaQuery: MediaQueryList | undefined

/** Radial gradients are allocation-heavy; rebuilt only when mood or size changes. */
let cached: { key: string; halo: CanvasGradient; body: CanvasGradient } | null = null

function draw(now: number): void {
  const element = canvas.value
  if (!element) return
  const context = element.getContext('2d')
  if (!context) return

  const width = element.clientWidth
  const height = element.clientHeight
  if (width === 0 || height === 0) return
  const ratio = window.devicePixelRatio || 1
  const pixelWidth = Math.round(width * ratio)
  const pixelHeight = Math.round(height * ratio)
  if (element.width !== pixelWidth || element.height !== pixelHeight) {
    element.width = pixelWidth
    element.height = pixelHeight
    cached = null
  }
  context.setTransform(ratio, 0, 0, ratio, 0, 0)
  // Clear in device pixels: a CSS-pixel rect leaves up to 1px of the old frame
  // whenever the ratio rounds up.
  context.clearRect(0, 0, width + 1, height + 1)

  const spec = MOODS[current.value]
  const sample = levels()
  // The graph, not a message counter, decides when the voice is over.
  markTalking(sample.talking)
  const driven = sample.rms > 0.0008 || sample.talking
  const centre = Math.min(width, height) / 2
  const clock = reduced ? 0 : now / 1000
  const pulse = Math.sin(clock * 1.6) * spec.breath
  // The real signal is added, not substituted: a voice at full amplitude grows the
  // core by about a fifth, which is enough to read as "this is talking" at a glance
  // and small enough that a shout cannot push the picture out of its own frame.
  const base = centre * (spec.radius + pulse + (driven ? sample.rms * 0.2 : 0))
  const [red, green, blue] = spec.color
  const cx = width / 2
  const cy = height / 2

  const gradientKey = `${current.value}|${pixelWidth}x${pixelHeight}`
  if (!cached || cached.key !== gradientKey) {
    const halo = context.createRadialGradient(cx, cy, base * 0.2, cx, cy, centre * 1.05)
    halo.addColorStop(0, `rgba(${red}, ${green}, ${blue}, 0.22)`)
    halo.addColorStop(1, 'rgba(0, 0, 0, 0)')
    const body = context.createRadialGradient(
      cx - base * 0.3,
      cy - base * 0.35,
      base * 0.1,
      cx,
      cy,
      base,
    )
    body.addColorStop(0, `rgba(${red}, ${green}, ${blue}, 0.5)`)
    body.addColorStop(0.65, `rgba(${red}, ${green}, ${blue}, 0.13)`)
    body.addColorStop(1, 'rgba(4, 10, 18, 0.85)')
    cached = { key: gradientKey, halo, body }
  }

  context.fillStyle = cached.halo
  context.fillRect(0, 0, width, height)
  context.lineCap = 'round'

  const spin = (clock * spec.spin * Math.PI) / 180
  const outer = centre * 0.92
  const gap = 0.075
  const step = TAU / 12
  context.lineWidth = 1.5
  for (let index = 0; index < 12; index += 1) {
    const start = spin + index * step
    context.beginPath()
    context.arc(cx, cy, outer, start + gap / 2, start + step - gap / 2)
    context.strokeStyle =
      index < spec.segments
        ? `rgba(${red}, ${green}, ${blue}, 0.55)`
        : `rgba(${red}, ${green}, ${blue}, 0.12)`
    context.stroke()
  }

  context.lineWidth = 2
  for (const [factor, direction, span] of [
    [0.78, 1, 0.5],
    [0.63, -1, 0.34],
  ] as const) {
    const start = direction * spin
    const radius = centre * factor
    context.beginPath()
    context.ellipse(cx, cy, radius, radius * spec.tilt, 0, start, start + TAU * span)
    context.strokeStyle = `rgba(${red}, ${green}, ${blue}, ${direction === 1 ? 0.7 : 0.34})`
    context.stroke()
  }

  context.beginPath()
  context.arc(cx, cy, base, 0, TAU)
  context.fillStyle = cached.body
  context.fill()
  context.lineWidth = 1
  context.strokeStyle = `rgba(${red}, ${green}, ${blue}, 0.8)`
  context.stroke()

  if (driven) drawSpectrum(context, cx, cy, base, sample, red, green, blue)
}

/**
 * The spectrum crown: five measured bands, mirrored around the core.
 *
 * Mirrored because a voice is not stereo, and an asymmetric ring reads as a graph
 * that lost half its data. The band edges are the pitch ranges a vowel actually
 * occupies, so the shape of the crown follows the shape of the syllable -- which is
 * the same measurement the 3D avatar will use for its mouth, and the reason the two
 * will move together rather than each inventing a rhythm.
 */
function drawSpectrum(
  context: CanvasRenderingContext2D,
  cx: number,
  cy: number,
  base: number,
  sample: { rms: number; peak: number; bands: number[] },
  red: number,
  green: number,
  blue: number,
): void {
  const spokes = 44
  const inner = base * 1.04
  /**
   * Loudness sets the reach, the bands set its shape.
   *
   * The scale is calibrated to measured speech, not to full-scale audio: an
   * edge-tts utterance sits around 0.02--0.08 RMS, so a reach proportional to the
   * raw number produces a crown a few pixels tall on a voice that is plainly
   * shouting. Dividing by a typical level makes "quiet", "talking" and "loud" three
   * visibly different pictures, which is the entire point of drawing it.
   */
  const loud = Math.min(1, sample.rms / 0.09)
  const reach = 0.1 + 0.3 * loud
  context.lineCap = 'round'
  for (let index = 0; index < spokes; index += 1) {
    const around = (index / spokes) * TAU
    // 0 → 1 → 0 across the circle, so the left half mirrors the right.
    const position = Math.abs(Math.sin((index / spokes) * Math.PI))
    const value = bandAt(sample.bands, position)
    const length = inner + reach * base * (0.3 + 0.7 * value)
    context.beginPath()
    context.moveTo(cx + Math.cos(around) * inner, cy + Math.sin(around) * inner)
    context.lineTo(cx + Math.cos(around) * length, cy + Math.sin(around) * length)
    context.lineWidth = 2
    context.strokeStyle = `rgba(${red}, ${green}, ${blue}, ${0.25 + value * 0.6})`
    context.stroke()
  }
}

/** Interpolated lookup so five measured bands make a smooth 44-spoke outline. */
function bandAt(bands: number[], position: number): number {
  if (bands.length === 0) return 0
  const scaled = Math.min(0.999, Math.max(0, position)) * (bands.length - 1)
  const from = Math.floor(scaled)
  const weight = scaled - from
  const next = bands[from + 1] ?? bands[from]
  return bands[from] * (1 - weight) + next * weight
}

function isAnimated(): boolean {
  if (talking.value) return true
  return !reduced && MOODS[current.value].spin > ANIMATED_BELOW
}

function stopLoop(): void {
  if (timer !== undefined) {
    clearInterval(timer)
    timer = undefined
  }
}

/**
 * A timer rather than requestAnimationFrame: rAF only throttles when the page is
 * hidden, and "minimised" is not the common case here -- the realistic one is a
 * visible window nobody is looking at, which rAF happily repaints at 60 Hz.
 *
 * While sound is playing the loop runs at the frame rate an amplitude envelope needs
 * (about 30 Hz: faster is invisible on a circle this small, slower makes the crown
 * stutter), and it drops back to the calm pulse rate the moment it stops. Nothing
 * repaints while it has nothing to say.
 */
function syncLoop(): void {
  stopLoop()
  if (!isAnimated()) return
  const interval = talking.value ? SPEAKING_FRAME_INTERVAL_MS : FRAME_INTERVAL_MS
  timer = setInterval(() => {
    if (document.hidden) return
    draw(performance.now())
  }, interval)
}

function repaint(): void {
  // A static mood still has to redraw when the state changes or the window resizes.
  cached = null
  draw(performance.now())
  syncLoop()
}

function onVisibility(): void {
  if (!document.hidden) repaint()
}

function onMotionChange(): void {
  reduced = mediaQuery?.matches ?? false
  repaint()
}

onMounted(() => {
  mediaQuery = window.matchMedia?.('(prefers-reduced-motion: reduce)')
  reduced = mediaQuery?.matches ?? false
  mediaQuery?.addEventListener('change', onMotionChange)
  document.addEventListener('visibilitychange', onVisibility)
  observer = new ResizeObserver(() => repaint())
  if (canvas.value) observer.observe(canvas.value)
  repaint()
})

onBeforeUnmount(() => {
  stopLoop()
  mediaQuery?.removeEventListener('change', onMotionChange)
  document.removeEventListener('visibilitychange', onVisibility)
  observer?.disconnect()
  observer = undefined
})

// The moment the state changes is the moment the picture has to change with it.
watch(current, repaint)
// Starting and stopping to speak changes how often the core has to be redrawn, and
// the last frame of a sentence is the one that removes the crown.
watch(talking, repaint)
</script>

<style scoped>
.core {
  display: flex;
  flex-direction: column;
  align-items: center;
  gap: 6px;
  min-height: 0;
}

/*
 * The core fills whatever height the rail gives it rather than capping at a fixed
 * square: the old layout left a void under a 168px orb, and the one element that is
 * supposed to be the focal point was not the largest thing on screen.
 */
.core__canvas {
  flex: 1;
  width: 100%;
  min-height: 0;
}

.core__readout {
  display: flex;
  flex-direction: column;
  align-items: center;
  gap: 4px;
  text-align: center;
  flex: none;
}

.core__state {
  font-size: 13px;
  letter-spacing: 0.16em;
  color: var(--core-accent, var(--hud-cyan));
  text-shadow: 0 0 18px var(--core-glow, rgba(77, 216, 255, 0.4));
  transition: color 0.3s ease;
}

/*
 * Two lines, no orphan. The hint used to be capped at 22ch, which wrapped
 * 「…免点击待命」 onto a third line carrying a single character.
 */
.core__hint {
  font-size: 11px;
  letter-spacing: 0.02em;
  line-height: 1.55;
  color: var(--hud-dim);
  max-width: 30ch;
  display: -webkit-box;
  -webkit-line-clamp: 2;
  -webkit-box-orient: vertical;
  overflow: hidden;
}

.core--armed {
  --core-accent: var(--hud-cyan);
  --core-glow: rgba(77, 216, 255, 0.4);
}
.core--listening {
  --core-accent: var(--hud-green);
  --core-glow: rgba(70, 230, 168, 0.45);
}
.core--thinking {
  --core-accent: var(--hud-violet);
  --core-glow: rgba(157, 124, 255, 0.45);
}
.core--waking,
.core--broken {
  --core-accent: var(--hud-amber);
  --core-glow: rgba(255, 181, 71, 0.4);
}
.core--error {
  --core-accent: var(--hud-red);
  --core-glow: rgba(255, 93, 93, 0.45);
}
.core--held,
.core--dormant {
  --core-accent: var(--hud-dim);
  --core-glow: rgba(107, 139, 164, 0.3);
}

/*
 * Speaking is a modifier, not a mood: the colour still comes from whether it is
 * listening, thinking or answering, and only the glow deepens. Replacing the mood
 * would make the core go the same colour for a typed reply read aloud and a spoken
 * turn, which are different things happening.
 */
.core--speaking .core__canvas {
  filter: drop-shadow(0 0 22px var(--core-glow, rgba(77, 216, 255, 0.45)));
}

.core__stop {
  margin-top: 2px;
  align-self: center;
}
</style>
