"""Measure where the Chinese recognition actually loses characters.

"语音识别有点垃圾" is a symptom, not a diagnosis, and the fix is different for each
of the three places the characters can go missing:

* the **model / decode** (wrong `language`, no ITN, beam settings),
* the **VAD segmentation** (sentences chopped at 500 ms pauses, first syllable
  clipped because the pad is too small),
* the **capture** (gain, sample rate, device).

So this runs the *same known text* down two paths and compares them: whole utterance
straight into the recogniser, versus frame-by-frame through the same segmenter the
voice pipeline uses. Both are scored with character error rate against the text we
synthesised, so the difference is a number and not an impression.

The audio is generated by Edge-TTS rather than recorded, which deliberately removes
the microphone from the measurement: if path A is clean and path B is not, the model
is fine and the pipeline is the problem, and no room acoustics are involved in that
conclusion.

    .venv/Scripts/python scripts/bench_asr.py
"""

from __future__ import annotations

import re
import sys
import time
from dataclasses import dataclass

from jarvis.asr.engines import SenseVoiceAsrEngine
from jarvis.config.schema import AsrSection, TtsSection, VadSection
from jarvis.tts.engines import EdgeTtsEngine
from jarvis.vad.engines import SileroVadEngine
from jarvis.vad.segmenter import VoiceActivitySegmenter

CAPTURE_RATE = 16_000

TAIL_SILENCE_S = 1.2
"""Longer than ``max_silence_ms`` so every utterance can close."""
"""What the microphone path and the ASR front-end both work in."""

# Sentences chosen to fail in the specific ways Chinese assistants fail: a number
# that needs inverse normalisation, a short imperative, a long sentence with a
# natural mid-sentence pause, and two near-homophones.
CASES: tuple[str, ...] = (
    "帮我把临时文件清理一下",
    "今天天气怎么样",
    "打开浏览器搜索二零二六年人工智能大会",
    "小夜，我想听你说说话，顺便看看磁盘还剩多少空间。",
    "把音量调到百分之三十然后静音三分钟",
)

_PUNCT = re.compile(r"[\s，。、？！：；,.?!:;\"'“”‘’（）()《》<>~·—\-]+")


def normalize(text: str) -> str:
    return _PUNCT.sub("", text)


def edit_distance(a: str, b: str) -> int:
    if not a:
        return len(b)
    previous = list(range(len(b) + 1))
    for i, ca in enumerate(a, start=1):
        current = [i]
        for j, cb in enumerate(b, start=1):
            current.append(min(previous[j] + 1, current[j - 1] + 1, previous[j - 1] + (ca != cb)))
        previous = current
    return previous[-1]


def cer(reference: str, hypothesis: str) -> float:
    reference = normalize(reference)
    hypothesis = normalize(hypothesis)
    if not reference:
        return 0.0
    return edit_distance(reference, hypothesis) / len(reference)


@dataclass
class Sample:
    text: str
    pcm16: bytes
    """s16le mono at :data:`CAPTURE_RATE`."""


def synthesise(engine: EdgeTtsEngine, text: str) -> bytes:
    """Edge-TTS gives 24 kHz s16le; collect the whole utterance."""
    chunks = [chunk.audio for chunk in engine.synthesize(text)]
    return b"".join(chunks)


def to_capture_rate(pcm24: bytes, source_rate: int) -> bytes:
    """Resample to 16 kHz the way the capture path would."""
    import numpy as np

    samples = np.frombuffer(pcm24, dtype="<i2").astype(np.float64)
    target = int(len(samples) * CAPTURE_RATE / source_rate)
    if target <= 0:
        return b""
    indices = np.linspace(0, len(samples) - 1, target)
    low = indices.astype(np.int64)
    high = np.minimum(low + 1, len(samples) - 1)
    weight = indices - low
    mixed = samples[low] * (1 - weight) + samples[high] * weight
    return np.clip(mixed, -32768, 32767).astype("<i2").tobytes()


def run_through_vad(asr: SenseVoiceAsrEngine, vad: VadSection, pcm: bytes) -> list[str]:
    """Feed the buffer exactly like ``VoicePipeline`` does, and transcribe each span."""
    segmenter = VoiceActivitySegmenter(
        SileroVadEngine(),
        sample_rate=CAPTURE_RATE,
        threshold=vad.threshold,
        min_speech_ms=vad.min_speech_ms,
        max_silence_ms=vad.max_silence_ms,
        speech_pad_ms=vad.speech_pad_ms,
        max_speech_ms=vad.max_speech_ms,
    )
    buffer = bytearray()
    out: list[str] = []
    frame = 512 * 2  # 512 samples of s16le, the pipeline's read size
    # Trailing silence, always. SPEECH_END only fires after ``max_silence_ms`` of
    # quiet, so a clip that ends on the last sample of speech can never close its
    # segment -- and a harness that forgets that reports "the VAD ate 61% of the
    # words" when it actually measured its own missing tail.
    pcm = pcm + bytes(int(CAPTURE_RATE * TAIL_SILENCE_S) * 2)
    for offset in range(0, len(pcm), frame):
        chunk = pcm[offset : offset + frame]
        buffer.extend(chunk)
        for event in segmenter.feed(chunk):
            if event.type.name == "SPEECH_END" and event.segment is not None:
                out.append(asr.recognize(bytes(buffer), segment=event.segment).text.strip())
    return out


def main() -> int:
    section = AsrSection(
        enabled=True,
        engine="sensevoice",
        model="iic/SenseVoiceSmall",
        language="auto",
        temperature=0.0,
        beam_size=5,
        device="cpu",
        punctuation=False,
    )
    vad = VadSection(
        enabled=True,
        engine="silero",
        threshold=0.5,
        min_speech_ms=250,
        max_silence_ms=500,
        speech_pad_ms=100,
        max_speech_ms=0,
    )
    tts = EdgeTtsEngine(
        TtsSection(
            enabled=True,
            engine="edge_tts",
            voice="zh-CN-XiaoxiaoNeural",
            speed=1.0,
            volume=1.0,
            device="cpu",
            model="",
        )
    )

    print("生成测试语音…")
    samples: list[Sample] = []
    for text in CASES:
        pcm24 = synthesise(tts, text)
        samples.append(Sample(text=text, pcm16=to_capture_rate(pcm24, tts.sample_rate)))
        print(f"  {len(samples[-1].pcm16) / 32000:.1f}s  {text}")

    print("\n加载 SenseVoice…")
    started = time.monotonic()
    asr = SenseVoiceAsrEngine(section)
    print(f"  {time.monotonic() - started:.1f}s")

    rows: list[tuple[str, float, float, float]] = []
    for sample in samples:
        auto = asr.recognize(sample.pcm16).text
        forced = asr.recognize(sample.pcm16, language="zh").text
        spans = run_through_vad(asr, vad, sample.pcm16)
        pipelined = "".join(spans)
        rows.append(
            (
                sample.text,
                cer(sample.text, auto),
                cer(sample.text, forced),
                cer(sample.text, pipelined),
            )
        )
        print(f"\n原文   : {sample.text}")
        print(f"auto   : {auto}")
        print(f"zh     : {forced}")
        print(f"VAD 切 : {spans}")

    def mean(index: int) -> float:
        return sum(row[index] for row in rows) / len(rows)

    print("\n" + "=" * 62)
    print(f"{'':<22}{'CER':>8}")
    print(f"{'整句 + language=auto':<22}{mean(1) * 100:>7.1f}%")
    print(f"{'整句 + language=zh':<22}{mean(2) * 100:>7.1f}%")
    print(f"{'过 VAD 切句':<22}{mean(3) * 100:>7.1f}%")
    print("=" * 62)
    return 0


if __name__ == "__main__":
    sys.exit(main())
